### ISSUE TITLE
Resolved

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [HackerHouseYT/AI-Smart-Mirror#10]
Resolved

**Comment by muratia** [comment]
As long as pip is not installed and virtualenv check the following information on both links I shared. I have little experience with Pythin and Django so I have used both of them.

https://pip.pypa.io/en/stable/installing/

http://sourabhbajaj.com/mac-setup/Python/virtualenv.html

**Comment by WilliamJamesDalrympleWest** [comment]
Apologies, it clicked immediately what was the issue, i just did not know where to update. 

Erm next issue, See you are using WitAI. 

_Replace wit.ai and darksky.net tokens in the bot.py file

Make sure MagicMirror is running, then start the AI

python bot.py_

Any details on how best to update, as there is no specific mention of what needs to be updated....

**Comment by muratia** [comment]
I do not have experience with SmartMirror but I have liked it a lot. If I relocate to Germany to work over there I am thinking to make such mirror.
