### ISSUE TITLE
Final Steps, issues, Please advise....

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [HackerHouseYT/AI-Smart-Mirror#13]
ooknams-Mac-mini:~ looknam$ cd AI-Smart-Mirror
Looknams-Mac-mini:AI-Smart-Mirror looknam$ deactivate
-bash: deactivate: command not found
Looknams-Mac-mini:AI-Smart-Mirror looknam$ source hhsmartmirror/bin/activate
(hhsmartmirror) Looknams-Mac-mini:AI-Smart-Mirror looknam$ deactivate
Looknams-Mac-mini:AI-Smart-Mirror looknam$ cd hhsmartmirror/lib/python2.7/site-packages
Looknams-Mac-mini:site-packages looknam$ cd hhsmartmirror/lib/python2.7/site-packages
-bash: cd: hhsmartmirror/lib/python2.7/site-packages: No such file or directory
Looknams-Mac-mini:site-packages looknam$ ls
PyAudio-0.2.9-py2.7.egg-info		py4j
SpeechRecognition-3.5.0-py2.7.egg-info	py4j-0.10.4.dist-info
_portaudio.so				pyaudio.py
dateutil				pyaudio.pyc
easy_install.py				pydub
easy_install.pyc			pydub-0.16.6.dist-info
feedparser-5.2.1-py2.7.egg-info		python_dateutil-2.6.0.dist-info
feedparser.py				requests
feedparser.pyc				requests-2.12.1.dist-info
gTTS-1.1.6-py2.7.egg-info		setuptools
gTTS_token-1.1.1-py2.7.egg-info		setuptools-29.0.0.dist-info
gtts					six-1.10.0.dist-info
gtts_token				six.py
numpy					six.pyc
numpy-1.11.2.dist-info			speech_recognition
pip					wheel
pip-9.0.1.dist-info			wheel-0.29.0.dist-info
pkg_resources
Looknams-Mac-mini:site-packages looknam$ cd ../../../..
Looknams-Mac-mini:AI-Smart-Mirror looknam$ source hhsmartmirror/bin/activate
(hhsmartmirror) Looknams-Mac-mini:AI-Smart-Mirror looknam$ python bot.py
/Users/looknam/AI-Smart-Mirror/hhsmartmirror/lib/python2.7/site-packages/pydub/utils.py:178: RuntimeWarning: Couldn't find ffplay or avplay - defaulting to ffplay, but may not work
  warn("Couldn't find ffplay or avplay - defaulting to ffplay, but may not work", RuntimeWarning)
Warning: OpenCV not installed. To use facial recognition, make sure you've properly configured OpenCV.
Found face
I'm listening
Found audio
Google Speech Recognition thinks you said where can you hear me hello hello
Found face
I'm listening

**Comment by ceased-ebc** [comment]
0
