### ISSUE TITLE
How/Where does the face come from and how do you activate it?

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [HackerHouseYT/AI-Smart-Mirror#16]
From the Hackaday video on their website you see a video in that video is the guide to the mirror, there is a cyber face, i can not find that cyber face, nor how to implement/activate it within the files, please advise....

[https://s16.postimg.org/ln4evh1sl/Screen_Shot_2016_12_01_at_14_09_21.png](url)

**Comment by atainter** [comment]
It is in the magic mirror module. To activate it, ask it what it looks like.
