### ISSUE TITLE
How to have the AI functioning alongside the MM Modules.

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [HackerHouseYT/AI-Smart-Mirror#17]
Our goal was to draw inspiration from this project: https://www.youtube.com/watch?v=sc9UbREmo58 Check it out for another interesting take on smart mirror AI.

Here you reference this mirror for the idea, however the video shows both MM and the AI functioning side by side, how can we implement the same?

**Comment by WilliamJamesDalrympleWest** [comment]
Still no information.

**Comment by atainter** [comment]
I have no idea what you mean. We wanted to build a similar project, so we made this code.
