### ISSUE TITLE
Issue with bot.py

### ISSUE THREAD

**Issue by arvidnilber** [HackerHouseYT/AI-Smart-Mirror#24]
This is what comes up when I try to start the bot. It listens and understands but doesn't go all the way. 

> python[5881:116623] 15:14:58.752 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**Comment by laststand0810** [comment]
take a look at this issue 2 years ago, might find some clue

https://github.com/cmus/cmus/issues/331

**Comment by leoofthecity** [comment]
can anyone plzz upload a video tutorial of this
