### ISSUE TITLE
Issue with microphone

### ISSUE THREAD

**Issue by akashtalole** [HackerHouseYT/AI-Smart-Mirror#4]
when I run python bot.py 
`Warning: OpenCV not installed. To use facial recognition, make sure you've properly configured OpenCV.
Used wrong endpoint for microphone debugging
Found face
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave
Used wrong endpoint for microphone debugging
I'm listening
Used wrong endpoint for microphone debugging
Found audio
Google Speech Recognition could not understand audio
Found face
`

**Comment by atainter** [comment]
Are you running this on linux?

**Comment by atainter** [comment]
You could try installing `flac`

**Comment by atainter** [comment]
You could also try updating pyaudio

**Comment by akashtalole** [comment]
Yes, I am using Ubuntu 15.10. @atainter will try above solutions.
