### ISSUE TITLE
trouble installing ffmpeg

### ISSUE THREAD

**Issue by emnabarred** [HackerHouseYT/AI-Smart-Mirror#40]
i had trouble with "brew install ffmpeg" it returns the following error:
*** Error in `/usr/bin/gcc-4.9': double free or corruption (top): 0x003cc718 ***
can anyone help please?

**Comment by muratia** [comment]
This error seems to be with memory, so if you could restart your computer and try again maybe this can resolve the issue.

**Comment by emnabarred** [comment]
@muratia I actually did that and it didn't work! but now I don't have that issue anymore I don't know what I did but I keept retrying and it worked haha

**Comment by muratia** [comment]
Sometimes the computers do not clean up the memory and in some programming languages likewise in C++ you have to allocate the memory and then to clean it up beforehand using it.
