### ISSUE TITLE
Error 111: Connection refused on RPI3

### ISSUE THREAD

**Issue by BenjaminUrquhart** [HackerHouseYT/AI-Smart-Mirror#54]
I have followed all the directions on how to install, but when I start the bot, I get this error:

HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /microphone?enabled=False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7136a450>: Failed to establish a new connection: [Errno 111] Connection refused',))

I have tracked this down to the Smart Mirror interface not opening port 8080 for some reason.

Any suggestions?

**Comment by aak2003** [comment]
Go to local Host 8080 and test with any statement then it would work or check your internet connection

**Comment by aak2003** [comment]
Start npm and then start bot.py

**Comment by BenjaminUrquhart** [comment]
I'm going to close this as I no longer run the mirror
