### ISSUE TITLE
bot.py "Cannot GET/clear"

### ISSUE THREAD

**Issue by wscotgrey** [HackerHouseYT/AI-Smart-Mirror#6]
Hey guys,

I'm setting up a test AI-Smart-Mirror/Magic Mirror on my Linux box before building a self installer for a smaller Linux setup for the actual mirror. I want to add to your AI features, like determining faces, Deep Learning databases for person specific interactions, and possibly interactive animations, so I'm not building on a PI, but using an old Netbook for the actual build. 

But I have a fairly standard Linux Mint desktop that I am configuring your Mac install to work on. After getting a lot of the install procedures to work here, I am stuck with the bot.py unable to speak to the browser. 

In your instructions, you test the browser by doing a localhost:8080/statement=whatever entry into the browser. My machine, which has no problem loading the MagicMirror to localhost, returns the statement command with "Cannot GET/statement=whatever"

I have disabled all firewalls, and stopped all other servers, and searched the interwebs to no conclusion. I am hoping you guys might have some input on why I am stuck. I hope this is the right place to ask, if not let me know and I'll drop the issue. 

Thanks again guys and this is a fun project! Found you guys on YouTube and am building the Retropie controller next! Thanks again!

Scot

**Comment by atainter** [comment]
That's very strange. I think this is more of a magic mirror issue though. Have you asked the guys on the MagicMirror project about this issue? It might be an issue with the way we define routes: (https://github.com/HackerHouseYT/AI-Smart-Mirror/blob/master/magic_mirror/aiclient/node_helper.js#L15) which is part of the MagicMirror codebase.
