### ISSUE TITLE
problem installing opencv on raspberry pi 3

### ISSUE THREAD

**Issue by pawan-saxena** [HackerHouseYT/AI-Smart-Mirror#65]
i am able to make the whole build on raspberry pi 3 and i want to contribute to this project but there are some problems that i am facing and they kind of aborted the whole process.

when i do brew install opencv i installs some packages but fails when trying to make binutils dependency.
ALso when i restart the pi the brew just goes off from it and i have to re-install it again and again

**Comment by cowboysdude** [comment]
They aren't going to help you.   They shouldn't be allowed to have a github account.  You don't put something out there and then not support it.  Just a bunch of hacks.

**Comment by pawan-saxena** [comment]
@cowboysdude basically i did resolved the issue and got successful in installing the whole or project on raspberry pi3.
I am running it on though it's a little bit slow but you can work around with the overclocking and it would be okay.
If you need any help i would be happy to.

**Comment by cowboysdude** [comment]
I appreciate that very much!!  I'm hoping that this becomes much more stable.  Right now I've written a ton of modules and am currently working on a multi provider weather module :)

**Comment by pawan-saxena** [comment]
That's very cool.  :+1:  
can you share with us the kin of work that you finished.
I would be very happy if we can come up with something cool we can build on pi.
As far as this smart mirror is concerned, it doesn't work very well; lot of lagging and command processing after the user said the phrase.
So i am looking for new projects that could run reasonably on pi.

Appreciate the kind of work you are doing.
