### ISSUE TITLE
Running bot.py and it says no module named 'requests'

### ISSUE THREAD

**Issue by kk1775** [HackerHouseYT/AI-Smart-Mirror#75]
I run python bot.py and I get this:
Traceback (most recent call last):
  File "bot.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
What's the problem? I'm using Win10. 
Can someone please tell me how to solve this?

**Comment by PoojaAmin29** [comment]
even i am getting the same error how to solve this issue
