### ISSUE TITLE
Found face traceback print error bot.py

### ISSUE THREAD

**Issue by aak2003** [HackerHouseYT/AI-Smart-Mirror#86]
When I run python bot.py I get an error saying
Line 41 
Print "Found face"

Missing parentheses ....(some other few words....) 'print'

Even though everything else works fine and even virtual environment is on

**Comment by aak2003** [comment]
Also it is a syntax error

**Comment by Josh4you** [comment]
Try Putting the line 41 as 
Print("Found Face ")


If possible it won't cause the next Nuclear Explosion.:)

**Comment by aak2003** [comment]
Thanks it worked
